### ISSUE TITLE
Bug about "Example Run"

### ISSUE THREAD

**Issue by SeanSiyang** [RobinMagnet/smoothFM#1]
Hi, I really appreciate your research on 3D shape correspondence :)

When I configured the conda environment and ran the code, I encountered the bug in the following figure：

![image](https://user-images.githubusercontent.com/65350848/212015054-87d54f79-82c2-49b6-94ab-90ad0f94fccc.png)

I don't know how to fix this bug, I hope you can help me~

Have a nice day~

**Comment by RobinMagnet** [comment]
Hi,

Thanks for your message :)

I see, the issue comes from my side as I forgot to add the example data to the repository (done now).
In this basic example, I used surfaces from the original FAUST dataset where shapes are in one to one correspondences. This assumption is used in the `generate_init_map` function.

However, it seems that you are using the remeshed version of FAUST (way better to evaluate methods), where the one to one correspondences assumption does not hold. You should therefore input you own dense initial map, _eg_ by using the ground truth maps provided with the remeshed dataset (downscaled with a similar strategy as in `generate_init_map`).

Let me know if you have trouble generating initial maps from the remeshed FAUST dataset !

Have a nice day

**Comment by SeanSiyang** [comment]
> Hi,
> 
> Thanks for your message :)
> 
> I see, the issue comes from my side as I forgot to add the example data to the repository (done now). In this basic example, I used surfaces from the original FAUST dataset where shapes are in one to one correspondences. This assumption is used in the `generate_init_map` function.
> 
> However, it seems that you are using the remeshed version of FAUST (way better to evaluate methods), where the one to one correspondences assumption does not hold. You should therefore input you own dense initial map, _eg_ by using the ground truth maps provided with the remeshed dataset (downscaled with a similar strategy as in `generate_init_map`).
> 
> Let me know if you have trouble generating initial maps from the remeshed FAUST dataset !
> 
> Have a nice day

Thanks, I will try to solve the problem according to what you said, thank you very much for your reply~
